### PR TITLE
Add copy button

### PR DESCRIPTION
**Pull request by steven4354**
**overview**

Alright if I add a copy button to chatcraft? 

It'd be great to be able to copy/paste the messages into docs easily

**demo**

Here's a demo of the changes

https://capture.dropbox.com/fdDadCi8oKKhZDd9

### CODE REVIEW

**Comment by tarasglek** [comment]
@humphd do you think this makes sense given upcoming share feature? Do we keep this for interim?

**Comment by steven4354** [comment]
cool! @humphd @tarasglek i could see myself using this copy almost every day so if this can be added and later on feel free to delete my add, that'd be great! thank you

**Comment by humphd** [comment]
@steven4354 can you give some thoughts on https://github.com/tarasglek/chatcraft.org/issues/72?

**Comment by steven4354** [comment]
sure! https://github.com/tarasglek/chatcraft.org/issues/72#issuecomment-1555253354

**Pull request merged**
