### PR TITLE
Migrate to Chakra V3

### PR DESCRIPTION
**Pull request by fadingNA**
- #701 

Migrate Chakra v2.8 -> v.3.0

### CODE REVIEW

**Comment by fadingNA** [comment]
@Amnish04 @humphd  @tarasglek 

This just a draft for you guys can track the progress or advicing

**Comment by humphd** [comment]
Why is this branch not using this repo?  I want to see previews as it happens.

**Comment by fadingNA** [comment]
let me change the remote to use this repo, from the fork one. @humphd

**Comment by fadingNA** [comment]
Waiting for invitation then will remote to this upstream branch, facing one issue 

Screenshot 2024-11-21 at 1 19 56 PM

**Comment by fadingNA** [comment]
@humphd  @tarasglek  @Amnish04  New version in progress 

New Version take full-w when sidebar toggle 

Screenshot 2024-11-21 at 8 08 04 PM
Screenshot 2024-11-21 at 8 08 16 PM

**Comment by Amnish04** [comment]
> @humphd @tarasglek @Amnish04 New version in progress
> 
> New Version take full-w when sidebar toggle
> 
> Screenshot 2024-11-21 at 8 08 04 PM 

@fadingNA Great progress! One thing I notice in the screenshots is that Chakra uses black theme by default in the new version. Can we switch that to match the current color scheme.

**Comment by fadingNA** [comment]
> > @humphd @tarasglek @Amnish04 New version in progress
> > New Version take full-w when sidebar toggle
> > Screenshot 2024-11-21 at 8 08 04 PM
> 
> @fadingNA Great progress! One thing I notice in the screenshots is that Chakra uses black theme by default in the new version. Can we switch that to match the current color scheme.

Yes because of the color codes has changed for the new version, will adjust for sure.

**Comment by fadingNA** [comment]
Screenshot 2024-11-22 at 1 14 24 AM

PreferencesModal Component, example.

**Comment by fadingNA** [comment]
Screenshot 2024-11-22 at 1 16 20 AM

Progress , Modal Preferences

**Comment by fadingNA** [comment]
Screenshot 2024-11-22 at 1 18 45 AM
> New Version

----

Screenshot 2024-11-22 at 1 18 49 AM

> Old Version [Bug overlap content]

**Pull request closed without merging**
