### PR TITLE
Allow using camera as input on mobile with gpt-4 vision

### LINKED ISSUE #282: Allow using camera as input on mobile with gpt-4 vision

### PR DESCRIPTION
**Pull request by mingming-ma**
Fix #282 

## Status

<details>

image

image

image
</details>

## Tasks

-  ~~Optimize the image locally so upload is faster~~ -> Will be tracked by #395 
- [x] There's a lot of horizontal scrolling on mobile (might be unrelated to this PR) 
    -> Will be fixed by new menu component, see result from #286 
- ~~The icon on mobile should probably be a camera~~ -> Changed to `Options` -> `Attach Files ...` 
- [x] Support the camera use case, but also attaching a photo from the camera roll

### CODE REVIEW

**Comment by humphd** [comment]
> This branch cannot be rebased due to conflicts

Same issue here.

Tested this with other users, and their feedback was:

1. Optimize the image locally so upload is faster
2. There's a lot of horizontal scrolling on mobile (might be unrelated to this PR)
3. The icon on mobile should probably be a camera
4. Support the camera use case, but also attaching a photo from the camera roll

**Comment by tarasglek** [comment]
@mingming-ma what's next here? I'm really excited for this to land

**Comment by mingming-ma** [comment]
@humphd Just tested mobile version and sending images works well. 

Since the `Attach` button is moved to the `Options` button, I removed the mobile view's `Camera` button, and user can add photos or take pictures from the `Options` button -> `Attach Files...`. and update the UI if needed in follow up PRs, Sounds good?

**Review by humphd — APPROVED** [review]
That makes sense.  When we start supporting other image types, we might want to separate "use camera" from "attach image", but let's wait.

**Review by WangGithub0 — APPROVED** [review]
Looks good.
photo library, take phone, choose files all work perfect.

**Comment by humphd** [comment]
This is so, so cool!  Just used it to take a picture of hand-written notes in order to get text. 💯

**Pull request merged**
