### PR TITLE
openrouter & other openai-compat model support

### PR DESCRIPTION
**Pull request by tarasglek**
Openrouter is neat in that it in theory gives us CC access and claude and open source models. They also support old-fashioned baseURL/token workflow, so easy to start to experiment with.

### 1.  Openrouter also does not support model listing
Ignore this, that was my bug.

### 2. Openrouter streaming does not work with langchain JS:
```
TypeError: Cannot read properties of undefined (reading 'function_call')
    at onmessage (openai.js:371:52)
    at onLine (event-source-parse.js:128:13)
    at onChunk (event-source-parse.js:92:13)
    at getBytes (event-source-parse.js:28:9)
    at async getResponse (axios-fetch-adapter.js:238:13)
    at async fetchAdapter (axios-fetch-adapter.js:176:18)
    at async RetryOperation._fn (index.js:50:12)
```
for some reason delta is null in their responses(I can't get browser devtools to show me SSE to debug further)
Here is unhappy code in langchain. Pretty sure every langchainjs streaming app is broken with them.
image
So when using non-openai models so I disable streaming for non-openai baseurls for now. We could probably do a smooth fallback for when streaming fails, but completion still comes in.

### 3. Our parsing of / in model names is a complete mess

Disabled it for now.

### 4. Our state management around preferences modal is pretty bad
Need to reload after adding baseurl

Proof that stuff works:
image

Feel free to try this with my key:
```
key: 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
baseurl: https://openrouter.ai/api/v1
```

@humphd I would like to land something like this. I think it's a good first step towards 3rd-party models. I just need @alexanderatallah to fix model-listing as hardcoding models is a no-go.

### CODE REVIEW

**Comment by tarasglek** [comment]
Ok so model listing was my bug. Got claude working now :)

**Comment by tarasglek** [comment]
image

**Comment by alexanderatallah** [comment]
Thanks for looping me in here. We have two conversations going on so I'm
going to move to the one in Discord
<https://discord.com/channels/1091220969173028894/1107397803266818229/1128661707217182720>,
but will copy my response here:

1) Correct me if I'm wrong, but sounds like you decided this is a bug on
your side? The /models endpoint should be returning all the models
correctly. All models are enabled for everyone, but once you run out of
your free trial, you'll receive 402s for paid models.

We could make a user-authed version of this endpoint that only returns free
models if you're out of credits, but I'm not sure how useful that would be
yet. What's the use case exactly?

2) Currently our streaming is returning "delta" for openai and "message"
for other models, and this is a mistake. Going to make sure we aren't
breaking anyone and then patch this asap.

**Comment by humphd** [comment]
I've updated and fixed some things, but there are some other things to consider and fix:

1. this breaks token counting logic when non-OpenAI models are used.  Have to consider this
2. switching between API URLs doesn't update the list of models, need to re-trigger that
3. switch between API URLs doesn't update the default model to use (e.g., still set to claude-2 when I switch back to OpenAI)
4. need icons for the new models to show in the messages view
5. need streaming to work with OpenRouter

I'll look at this again tonight or tomorrow, but it's mostly usable.

**Comment by humphd** [comment]
Pushed another commit to fix 4. above, adding icons for the new models:

Screenshot 2023-07-12 at 5 16 44 PM

I've also renamed "OpenAiMessage" to "AiMessage" to reflect that it's no longer only OpenAI.

**Comment by humphd** [comment]
I also found that trying to prompt the `falcon-40b-instruct` model fails with a `530` and an HTML page as the error, which seems wrong.

Buried in that page is `Please enable cookies.`, which I have enabled, but it might be breaking at the boundary with OpenRouter.  Doesn't seem to be our bug:

```json
{
    "error": {
        "message": "<!DOCTYPE html>\n<!--[if lt IE 7]> <html class=\"no-js ie6 oldie\" lang=\"en-US\"> <![endif]-->\n<!--[if IE 7]>    <html class=\"no-js ie7 oldie\" lang=\"en-US\"> <![endif]-->\n<!--[if IE 8]>    <html class=\"no-js ie8 oldie\" lang=\"en-US\"> <![endif]-->\n<!--[if gt IE 8]><!--> <html class=\"no-js\" lang=\"en-US\"> <!--<![endif]-->\n<head>\n<title>Origin DNS error | p5f53oafbks8eybf.us-east-1.aws.endpoints.huggingface.cloud | Cloudflare</title>\n<meta charset=\"UTF-8\" />\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\" />\n<meta name=\"robots\" content=\"noindex, nofollow\" />\n<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\" />\n<link rel=\"stylesheet\" id=\"cf_styles-css\" href=\"/cdn-cgi/styles/main.css\" />\n\n\n<script>\n(function(){if(document.addEventListener&&window.XMLHttpRequest&&JSON&&JSON.stringify){var e=function(a){var c=document.getElementById(\"error-feedback-survey\"),d=document.getElementById(\"error-feedback-success\"),b=new XMLHttpRequest;a={event:\"feedback clicked\",properties:{errorCode:1016,helpful:a,version:1}};b.open(\"POST\",\"https://sparrow.cloudflare.com/api/v1/event\");b.setRequestHeader(\"Content-Type\",\"application/json\");b.setRequestHeader(\"Sparrow-Source-Key\",\"c771f0e4b54944bebf4261d44bd79a1e\");\nb.send(JSON.stringify(a));c.classList.add(\"feedback-hidden\");d.classList.remove(\"feedback-hidden\")};document.addEventListener(\"DOMContentLoaded\",function(){var a=document.getElementById(\"error-feedback\"),c=document.getElementById(\"feedback-button-yes\"),d=document.getElementById(\"feedback-button-no\");\"classList\"in a&&(a.classList.remove(\"feedback-hidden\"),c.addEventListener(\"click\",function(){e(!0)}),d.addEventListener(\"click\",function(){e(!1)}))})}})();\n</script>\n\n<script defer src=\"https://performance.radar.cloudflare.com/beacon.js\"></script>\n</head>\n<body>\n  <div id=\"cf-wrapper\">\n    <div class=\"cf-alert cf-alert-error cf-cookie-error hidden\" id=\"cookie-alert\" data-translate=\"enable_cookies\">Please enable cookies.</div>\n    <div id=\"cf-error-details\" class=\"p-0\">\n      <header class=\"mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-15 antialiased\">\n         <h1 class=\"inline-block md:block mr-2 md:mb-2 font-light text-60 md:text-3xl text-black-dark leading-tight\">\n           <span data-translate=\"error\">Error</span>\n           <span>1016</span>\n         </h1>\n         <span class=\"inline-block md:block heading-ray-id font-mono text-15 lg:text-sm lg:leading-relaxed\">Ray ID: 7e5c48f876812090 &bull;</span>\n         <span class=\"inline-block md:block heading-ray-id font-mono text-15 lg:text-sm lg:leading-relaxed\">2023-07-12 21:12:33 UTC</span>\n        <h2 class=\"text-gray-600 leading-1.3 text-3xl lg:text-2xl font-light\">Origin DNS error</h2>\n      </header>\n\n      <section class=\"w-240 lg:w-full mx-auto mb-8 lg:px-8\">\n          <div id=\"what-happened-section\" class=\"w-1/2 md:w-full\">\n            <h2 class=\"text-3xl leading-tight font-normal mb-4 text-black-dark antialiased\" data-translate=\"what_happened\">What happened?</h2>\n            <p>You've requested a page on a website (p5f53oafbks8eybf.us-east-1.aws.endpoints.huggingface.cloud) that is on the <a href=\"https://www.cloudflare.com/5xx-error-landing/\" target=\"_blank\">Cloudflare</a> network. Cloudflare is currently unable to resolve your requested domain (p5f53oafbks8eybf.us-east-1.aws.endpoints.huggingface.cloud).\n            \n          </div>\n\n          \n          <div id=\"resolution-copy-section\" class=\"w-1/2 mt-6 text-15 leading-normal\">\n            <h2 class=\"text-3xl leading-tight font-normal mb-4 text-black-dark antialiased\" data-translate=\"what_can_i_do\">What can I do?</h2>\n            <p><strong>If you are a visitor of this website:</strong><br />Please try again in a few minutes.</p><p><strong>If you are the owner of this website:</strong><br />Check your DNS settings. If you are using a CNAME origin record, make sure it is valid and resolvable. <a rel=\"noopener noreferrer\" href=\"https://support.cloudflare.com/hc/en-us/articles/234979888-Error-1016-Origin-DNS-error\">Additional troubleshooting information here.</a></p>\n          </div>\n          \n      </section>\n\n      <div class=\"feedback-hidden py-8 text-center\" id=\"error-feedback\">\n    <div id=\"error-feedback-survey\" class=\"footer-line-wrapper\">\n        Was this page helpful?\n        <button class=\"border border-solid bg-white cf-button cursor-pointer ml-4 px-4 py-2 rounded\" id=\"feedback-button-yes\" type=\"button\">Yes</button>\n        <button class=\"border border-solid bg-white cf-button cursor-pointer ml-4 px-4 py-2 rounded\" id=\"feedback-button-no\" type=\"button\">No</button>\n    </div>\n    <div class=\"feedback-success feedback-hidden\" id=\"error-feedback-success\">\n        Thank you for your feedback!\n    </div>\n</div>\n\n\n      <div class=\"cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300\">\n  <p class=\"text-13\">\n    <span class=\"cf-footer-item sm:block sm:mb-1\">Cloudflare Ray ID: <strong class=\"font-semibold\">7e5c48f876812090</strong></span>\n    <span class=\"cf-footer-separator sm:hidden\">&bull;</span>\n    <span id=\"cf-footer-item-ip\" class=\"cf-footer-item hidden sm:block sm:mb-1\">\n      Your IP:\n      <button type=\"button\" id=\"cf-footer-ip-reveal\" class=\"cf-footer-ip-reveal-btn\">Click to reveal</button>\n      <span class=\"hidden\" id=\"cf-footer-ip\">2a06:98c0:3600::103</span>\n      <span class=\"cf-footer-separator sm:hidden\">&bull;</span>\n    </span>\n    <span class=\"cf-footer-item sm:block sm:mb-1\"><span>Performance &amp; security by</span> <a rel=\"noopener noreferrer\" href=\"https://www.cloudflare.com/5xx-error-landing\" id=\"brand_link\" target=\"_blank\">Cloudflare</a></span>\n    \n  </p>\n  <script>(function(){function d(){var b=a.getElementById(\"cf-footer-item-ip\"),c=a.getElementById(\"cf-footer-ip-reveal\");b&&\"classList\"in b&&(b.classList.remove(\"hidden\"),c.addEventListener(\"click\",function(){c.classList.add(\"hidden\");a.getElementById(\"cf-footer-ip\").classList.remove(\"hidden\")}))}var a=document;document.addEventListener&&a.addEventListener(\"DOMContentLoaded\",d)})();</script>\n</div><!-- /.error-footer -->\n\n\n    </div><!-- /#cf-error-details -->\n  </div><!-- /#cf-wrapper -->\n\n  <script>\n  window._cf_translation = {};\n  \n  \n</script>\n\n</body>\n</html>\n",
        "code": 530
    }
}
```

**Comment by tarasglek** [comment]
This is a huge feature. Lets land this and continue improving in followups

**Comment by humphd** [comment]
I'm cool to land this and iterate.  Some questions/issues I have for later issues/PRs:

1. Is `falcon-40b-instruct` actually usable?  If not, we should filter out of model list from OpenRouter
2. Is Google Bard supported?  I don't have access in Canada, so maybe it's just me.  If it exists, I need to add an icon
3. Need to fix stat changes in `apiUrl` and `apiKey` to reload models, set default model back to `gpt-3.5-turbo` (i.e., don't continue using `claude-2` or something when switching back to OpenAI)
4. Figure out a plan for token counting on non-OpenAI models, since we currently use tiktoken.  Maybe we get this as part of OpenRouter?  Haven't checked.
5. Fix model name parsing to properly deal with `vendor/model-name`

**Pull request merged**
