### PR TITLE
Turn Send button into Ask + model chooser

### PR DESCRIPTION
**Pull request by humphd**
Make it easier to switch models.  The "Send" button is now "Ask" with a menu that lets you change models.  I shortened "Single Message Mode" to drop the "Mode" so it fits on mobile.

Screenshot 2023-06-07 at 12 02 57 PM
Screenshot 2023-06-07 at 12 02 49 PM
Screenshot 2023-06-07 at 12 02 39 PM

### CODE REVIEW

**Comment by tarasglek** [comment]
it's convenient, but it bugs me to have so many choosers.

**Comment by tarasglek** [comment]
just realized that clicking "ask" button doesn't do anything :) this has been broken prior to ths pull req too :)

**Comment by humphd** [comment]
WFM.  Do you have anything in the form when you click it?

**Comment by tarasglek** [comment]
my bad. Got confused made same mistake twice

**Pull request merged**
