### PR TITLE
sorting the retry options and created a separate submenu under retry with button the menu

### LINKED ISSUE #316: make "retry with" a submenu
maybe even multiple levels of submenus with some fixed number of entries each. 
Here is what openrouter looks like, it's only gonna get worse:
image

Can probably get gpt to group entries for us via function call.

### PR DESCRIPTION
**Pull request by Rachit1313**
fixes #316 

Changes Made:

- [x] Created a submenu menu list under retry with menu button
- [x] sorted the list alphanumerically

Screenshot 2024-01-16 at 5 29 04 PM
Screenshot 2024-01-16 at 5 29 12 PM

### CODE REVIEW

**Comment by humphd** [comment]
Adding @kliu57 for review, since she's been focused on ChakraUI this week, and has also worked on code that's related to this.

**Review by humphd — CHANGES_REQUESTED** [review]
It's not clear that the "Retry With" menu item is clickable, or a sub-menu:

Screenshot 2024-01-16 at 7 46 18 AM

Compare that to native menus on my Mac:

Screenshot 2024-01-16 at 7 47 27 AM

We need some kind of arrow to indicate that you can open a list if you click.  Compare to how the `Ask...` button works:

Screenshot 2024-01-16 at 7 48 10 AM

In this case, we might want the arrow pointing down or to the right.

**Comment by Rachit1313** [comment]
> It's not clear that the "Retry With" menu item is clickable, or a sub-menu:
> 
> Screenshot 2024-01-16 at 7 46 18 AM
> Compare that to native menus on my Mac:
> 
> Screenshot 2024-01-16 at 7 47 27 AM
> We need some kind of arrow to indicate that you can open a list if you click. Compare to how the `Ask...` button works:
> 
> Screenshot 2024-01-16 at 7 48 10 AM
> In this case, we might want the arrow pointing down or to the right.

Thank you for your suggestion. I just made the changes.

**Review by Rachit1313 — COMMENTED** [review]
done. thanks

**Comment by Rachit1313** [comment]
Screenshot 2024-01-16 at 8 32 54 PM
Screenshot 2024-01-16 at 8 33 09 PM

**Comment by humphd** [comment]
A few things to fix:

- This shouldn't look like a button, it should look like the other menu items (e.g., no blue background, same font colour, etc)
- It shouldn't be centered, but left-aligned like the other items

**Comment by tarasglek** [comment]
Can we make this just about sorting and sort out submenu in a followup?

**Comment by humphd** [comment]
Sure, sorry for scope creep (though he's fixed it now).

**Comment by tarasglek** [comment]
that menu does not work well for me on mobile

**Comment by Rachit1313** [comment]
> Can we make this just about sorting and sort out submenu in a followup?

Done #344

**Pull request closed without merging**
