### PR TITLE
Add twitter card metadata

### LINKED ISSUE #432: Add twitter card metadata
Silly twitter doesn't render OG in our shared chats, eg https://chatcraft.org/api/share/tarasglek/5szbfO7gPyjwQLzJE96wb

Need to add twitter-specific cards mentioned in https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/abouts-cards

### PR DESCRIPTION
**Pull request by rjwignar**
This fixes #432.

Summary
---
- Added an `og:type` property.
From https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/markup,
image
A Twitter Summary card can be rendered if an `og:type`, `og:title` and `og:description` exist but not `twitter:card`, but I ended up also adding required Twitter meta tags for robustness.
- added Twitter meta tags required to render a Summary Card w/ Image

Testing Requirements?
---
I am going to run the generated preview against the [Twitter Card Validator](https://cards-dev.twitter.com/validator).
I hope the validator can test the preview website

### CODE REVIEW

**Comment by humphd** [comment]
In a follow-up, I'd like to see us take a screenshot of the final message, and upload that along with the chat when we share, and we could use it as our image.  For now, no image is fine.

**Review by humphd — CHANGES_REQUESTED** [review]
This is a good start.

But can you add it to the share logic too?

https://github.com/tarasglek/chatcraft.org/blob/4016e91a955822d1119fd3a5d90b24e3bc4af907/src/lib/share.ts#L59

**Review by kliu57 — APPROVED** [review]
Just tested on twitter with the preview url, works well.

image

**Review by humphd — APPROVED** [review]

**Comment by rjwignar** [comment]
Tested Twitter meta tags in shared chat, https://rjwignar-issue-432.console-overthinker-dev.pages.dev/api/share/chatcraft_dev/BD3ThijHaa5gfs51H0JEN, against Twitter Card validator and it passes:
image

Here's what it looks like in the Tweet Composer (using summary_large_image):
image

>In a follow-up, I'd like to see us take a screenshot of the final message, and upload that along with the chat when we share, and we could use it as our image. For now, no image is fine.

TODO in followup: Modify twitter:image meta tags to use screenshot of final message.

**Pull request merged**
