### PR TITLE
Initial experiment adding slash commands

### PR DESCRIPTION
**Pull request by humphd**
This is an initial attempt to add "slash commands."  I'm not 100% sure about the UX yet, so I'm hoping that we can play with this PR and figure it out together.

A command is something a user enters in the prompt, and starts with `/`.  Currently, there are 4 commands defined:

1. `/new` creates a new blank chat
2. `/clear` clears the messages in the current chat
3. `/summary` or `/summary <word count>` creates a summary of the current chat, using `word count`.  For example, `/summary 15` would summarize in at most 15 words
4. `/github <github code URL>` fetches the file at the given GitHub URL and adds it to the chat as if you copy/pasted it.  For example: `/github https://github.com/tarasglek/chatcraft.org/blob/main/src/lib/summarize.ts`

See what you think and we can iterate.

### CODE REVIEW

**Comment by tarasglek** [comment]
I like where this is going, but this particular approach feels too object-oriented and isn't extensible.

1) we should have a mapping of functions + /commands 
2) mapping should be extensible via prompting/system-message just like we do with functions
eg I wanna make a chatcraft resume-review tool where i have an /approve and /reject commands that call my functions
3) we should delete command specifications from msg history ala #209 
4) I would like to define pre-existing commands in same way as user commands would be defined, except maybe the js for them is hosted on /chatcraft-commands/url.js

**Comment by humphd** [comment]
Added an `/import <url>` command, which proxy's a `fetch()` through a Pages Function so that CORS isn't an issue.

This could be extended to to post processing, for example:

```
# load the text at example.com into a message
/import http://example.com

# load a PDF and get the text out of it, putting into a message. Second arg specifies type
/import http://example.com/file.pdf pdf
```

The pages function requires you to be logged in (like sharing) so we avoid people abusing proxy endpoint.  I don't know if it will work until it's pushed to prod, but it works locally if I comment out the security checks in `proxy.ts` and run `pnpm dev-functions` locally.

**Comment by tarasglek** [comment]
we really should sort out a staging env, so server-side functionality should be tested

**Comment by humphd** [comment]
agreed, it's a total pain to do this dev work now

**Comment by humphd** [comment]
Let's get #217 landed so this is easier to test

**Comment by humphd** [comment]
I've rebased this so that people can test on staging or locally.  I've also made the `/import <url>` command smarter for GitHub URLs.

Things to try (you need to login before you can run `/import`):

```
# Pull in raw content of a gist
/import https://gist.github.com/humphd/647bbaddc3099c783b9bb1908f25b64e

# Pull in a file from GitHub
/import https://github.com/jsdom/whatwg-mimetype/blob/master/scripts/get-latest-platform-tests.js

# Pull in a blog post's HTML
/import https://taras.glek.net/post/overlooked-hn-databases-that-process-data-faster-than-memory-bandwidth/
```

**Comment by tarasglek** [comment]
`/help` gave me this
image

**Comment by tarasglek** [comment]
`/load` fails when not logged in, doesn't tell you why

**Comment by tarasglek** [comment]
I used `/load https://taras.glek.net/post/overlooked-hn-databases-that-process-data-faster-than-memory-bandwidth/index.md`, then asked chatcraft to be an editor and it gave me helpful feedback

chatcraft should show /commands that were run in history

I like this functionality a lot!

**Comment by humphd** [comment]
OK, I'll add a `/help`, which is something we've needed forever anyway.

When you say `/load` do you mean `/import`?  Should I rename it to `/load` or support both?

For this:

> chatcraft should show /commands that were run in history

So I should add a message (app message?) to the chat showing that you typed `/whatever`?

**Comment by tarasglek** [comment]
I'm ok just making it look like a "/load" function call, it's same thing with mechanics basically

**Comment by humphd** [comment]
I've added a `/help` command (using `help` will also work), and made a note in the prompt form's default placeholder.

It will show a more comprehensive help message.  Please see if you think it's good, what needs to be added, etc.

I've added an error message about not being logged in for `/import`.

I'm still unclear on what you want me to do with the naming of `/import` vs. `/load`

**Comment by tarasglek** [comment]
Do as you wish re /load,  load implies less conversion

**Comment by tarasglek** [comment]
> So I should add a message (app message?) to the chat showing that you typed /whatever?

Yes. I think it should just have function call formatting
image
Function Call: load
load(url)

**Comment by humphd** [comment]
@iramykytyn would you mind reviewing how the `/help` command works in this PR?  I'm trying to build in some help for totally new users (I think you've worked with some, based on what Taras has said?).

If you're willing, please let me know if it's too much, not enough, needs more or different examples, etc.

I know we'll need proper docs at some point, but I want something to get people over the "now what?" point of using ChatCraft.

**Comment by tarasglek** [comment]
we should land this

**Comment by humphd** [comment]
Added command info to response message for `/import` and `/summary`:

Screenshot 2023-08-25 at 9 09 06 PM

I'll land when this goes green.

**Pull request merged**
