### PR TITLE
Use better icons for llama, Gemini, and other models, Issue-#675

### PR DESCRIPTION
**Pull request by hpatel292-seneca**
In this PR, I’ve updated the `logoUrl` function in `ChatCraftModel.ts` to improve the icon selection for several new AI models, including **Llama**, **Gemini**, **Mixtral**, and **Phi**. I’ve added relevant icons for these models and ensured they display properly in the UI. The new icons were sourced and added to the assets folder, and now each model from providers like Meta, Google, and others has a unique, recognizable logo. This helps enhance the user interface by providing more visually distinct and accurate model representations.

### CODE REVIEW

**Comment by hpatel292-seneca** [comment]
image
image
image
image

**Comment by humphd** [comment]
Lets reduce the size of these as much as you can.  We're only going to show them in a very small width x height area, and also the quality can be reduced.

Use something like https://squoosh.app/ and make them all PNG.

**Comment by hpatel292-seneca** [comment]
I converted the jpg to png but the size of new logos is kind of same compare to other logos.
image

**Comment by humphd** [comment]
Probably the existing ones need to get fixed too, but this looks reasonable.

**Comment by hpatel292-seneca** [comment]
I didn't push new changes. Let me do that first

**Comment by humphd** [comment]
I was just going to ask... :)

**Comment by hpatel292-seneca** [comment]
I pushed new changes.

**Review by humphd — APPROVED** [review]
Let's try it.  Thanks for doing this @hpatel292-seneca, it's appreciated.

**Comment by humphd** [comment]
Testing this in prod, looks good!

Screenshot 2024-10-02 at 3 36 42 PM

One thing I wonder about: should we change the llama check so it just looks for llama in the name?  Otherwise only `meta-llama` comes up with an icon.

I'd be tempted to use it for all of them, since it's the same model.

**Comment by hpatel292-seneca** [comment]
I would love to update it. Should I?

**Comment by humphd** [comment]
In a new PR? sure.

**Comment by hpatel292-seneca** [comment]
So could you please open new issue or should I send PR directly?

**Comment by humphd** [comment]
Just send a PR, reference this issue (e.g., "Part of #690")

**Pull request merged**
