### PR TITLE
Refactor ChatCraftMessage to support AI Versions

### PR DESCRIPTION
**Pull request by humphd**
Part of #59

The following changes update the type system and db in order to support adding `versions` to `ChatCraftAiMessage`s.  It also does a migration to introduction a new optional `versions` property in the db.

I've removed/moved a bunch of utilities and gutted the `useMessages()` hook, since none of that code is right anymore.  The token counting needs to get fixed, but we can do that as part of #61.

I have only tested this lightly, so I'll look at it again before landing.

After this is in, the focus can switch to the UI and being able to retry an AI Message with a different model.

### CODE REVIEW

**Comment by humphd** [comment]
This is functional now, and extends what I did previously on the types/db to add UI support for retrying AI messages with different models in order to produce new versions and then switch between those versions.

I've also included my work from #100 to allow editing any message's text, since it's connected with this work.  When editing an AI message, I add another version (i.e., so you can go back).

Here are some screenshots of what it looks like:

## Get back a response, use new "Retry..." menu options to try with another model
Screenshot 2023-06-08 at 4 04 06 PM

## New version is streamed into current message
Screenshot 2023-06-08 at 4 04 20 PM

## When a message has multiple versions, new UI lets you switch between them
Screenshot 2023-06-08 at 4 04 35 PM

## Clicking "Edit" allows editing in place
Screenshot 2023-06-08 at 4 04 49 PM

I think this opens up some interesting workflows:

- I am no longer constrained by aspects of a response I don't like.  Everything is text, and all text is editable.  Further, I am the author of all text (e.g., what the AI responds with is equally part of the "text I am working on").
- I am no longer constrained by the choice of model in a previous step.  Every response can be retried with a different model, but also with a different context (e.g., if you edit or retry previous messages, you build a new context for the response).

There are aspects of what I'm doing here that could be cleaned-up in the code, but I didn't bother to perfect things until it's clear on UX direction we want to take.  Having something to test and discuss will hopefully make that easier.

cc @niallo

**Comment by niallo** [comment]
I love this approach! In particular making everything "text I am working on" and having multiple versions you can switch between. Nice job - I look forward to hopefully trying it once it is ready.

**Comment by tarasglek** [comment]
> I love this approach! In particular making everything "text I am working on" and having multiple versions you can switch between. Nice job - I look forward to hopefully trying it once it is ready.

@niallo fyi we have previews for all pull requests. just click on 
image
then 
image

**Comment by tarasglek** [comment]
image

This is too complex. We should combine gpt-4/versions. Eg if we already generated chatgpt version too then

|GPT-4 🔽                       | [Jun 9, 2023, 12:02 PM]
| ChatGPT-3.5 [Jun 9, 2023, 12:01 PM] |
-----------------------------
| Retry with ChatGPT-3.5  |
| Retry with GPT-4            |

This way can have multiple generations and can extend this in the future for passing other model params

**Comment by tarasglek** [comment]
Other issue that if i started with chatgpt, then switched model to gpt-4, i would expect subsequent messages to use gpt-4...but this now changes your submission logic where you pick model from previous message and it gets weird with welcome message..so we can leave this for followup

**Comment by tarasglek** [comment]
btw, i also think we shouldn't submit welcome message to gpt..it should just be a message from chatcraft.

**Comment by humphd** [comment]
I think putting versions in the menu is not obvious, and will clutter menu.

Putting an indicator in the header of the message borrows from what GtiHub does with edited versions of comments in issues/PRs:

Screenshot 2023-06-09 at 8 05 37 AM

For example, you often edit stuff in GitHub, and I will go to an issue and see "edited" and know that it's been updated.  Similarly, if there are multiple versions of something, I'd like to have an indicator that they exist.

What does "this is too complex" mean exactly?  So, I'm hearing:

- add timestamp beside model name
- don't say "version" but somehow turn the name/timestamp into a drop-down instead?

If so, that's interesting.  The downside of this is that the timestamp is the link to this message, so you can't have it be a link and a drop-down.

Can you file unrelated stuff (e.g., "don't send welcome message...") in other issues so we don't lose?

**Comment by tarasglek** [comment]
I wanna be clear, this functionality is fantastic and makes chatcraft even more of a joy to use, but I wanna simplify it more.

> What does "this is too complex" mean exactly? 

In the this pr: we to the side menu to ask another model for response..and then switch between model responses in 2nd menu..and also indicate chatgpt/gpt-4 in 3rd indicator.

That makes the titlebar cluttered with redundant info without much grouping of related functionality.

>So, I'm hearing:
> 
> * add timestamp beside model name
> * don't say "version" but somehow turn the name/timestamp into a drop-down instead?

Yes

Ok. will file separate issues for other stuff.

**Comment by humphd** [comment]
Playing with this locally, here's another iteration:

Screenshot 2023-06-12 at 10 36 51 PM
Screenshot 2023-06-12 at 10 37 00 PM

I don't want to mix Actions and State in the 3-dots menu, which should all be Actions.  I think having this chevron and drop-down menu where the Avatar, Name, and Date sit makes sense.

**Comment by humphd** [comment]
Pushed my code if you want to test.  It's not ready to land, but it's getting closer.

**Comment by tarasglek** [comment]
Current version is very slick.

**Comment by humphd** [comment]
@niallo this is live on chatcraft.org, if you want to play with it now.  Try it out and file feedback on ways to improve it.

**Pull request merged**
