### PR TITLE
Feed icon open raw feed

### LINKED ISSUE #572: Feed icon should open raw feed
I find it surprising that clicking the new "Feed" button copies the feed URL to your clipboard vs. opening that in a new tab:

Screenshot 2024-04-07 at 2 14 22 PM

I think this should be an `<a target="_blank">...` that simply opens it for you.

### PR DESCRIPTION
**Pull request by WangGithub0**
Change Feed icon directly open raw feed tab

closes #572

### CODE REVIEW

**Review by Amnish04 — COMMENTED** [review]
@WangGithub0 The code looks good, and the button leads us to a new tab now.

I had a question. Clicking this button downloads a `.atom` file for me, which gives me an error when trying to import in [Feeder](https://feeder.co/library/import-export). Is this the expected behaviour or should we be seeing XML for the feed?

**Comment by Rachit1313** [comment]
> @WangGithub0 The code looks good, and the button leads us to a new tab now.
> 
> I had a question. Clicking this button downloads a `.atom` file for me, which gives me an error when trying to import in [Feeder](https://feeder.co/library/import-export). Is this the expected behaviour or should we be seeing XML for the feed?

Hi Amnish,
Which OS did you test this on. i tested it today on macOS but no file was downloaded for me and I was redirected to a new tab with the feed? Is the above behavior windows specific?

**Comment by Amnish04** [comment]
> > @WangGithub0 The code looks good, and the button leads us to a new tab now.
> > I had a question. Clicking this button downloads a `.atom` file for me, which gives me an error when trying to import in [Feeder](https://feeder.co/library/import-export). Is this the expected behaviour or should we be seeing XML for the feed?
> 
> Hi Amnish, Which OS did you test this on. i tested it today on macOS but no file was downloaded for me and I was redirected to a new tab with the feed? Is the above behavior OS specific?

@Rachit1313 I am using Firefox on Windows 10. But for me, a file gets downloaded

**Comment by Amnish04** [comment]
> @Amnish04 @Rachit1313 thanks for your testing, my test is open a new tab with feed.atom file.

@WangGithub0 Yes, the new tab is opening. Just that the file gets downloaded. Maybe my browser issue?

**Comment by WangGithub0** [comment]
> > @Amnish04 @Rachit1313 thanks for your testing, my test is open a new tab with feed.atom file.
> 
> @WangGithub0 Yes, the new tab is opening. Just that the file gets downloaded. Maybe my browser issue?

could you try this "open code in new window" button?
image

**Review by Rachit1313 — APPROVED** [review]

**Comment by Rachit1313** [comment]
@Amnish04 , I even tested it on my Windows Chrome and it works well for me and no file is downloaded. Maybe its something firefox related.

**Review by Amnish04 — APPROVED** [review]
Maybe something specific to my browser I guess if its working for everyone else.

Looks good otherwise!

**Pull request merged**
