### PR TITLE
add /stats command for perf stats, trace dexie reads

### PR DESCRIPTION
**Pull request by tarasglek**
@humphd ok to land this? Can see some pretty obvious things we shouldn't be doing.

I was gonna do some opentelemetry stuff and setup backends to analyze perf..but figured I'd start by instrumenting code...turns out all the libs that we use also use `PerformanceObserver` api, pretty cool

### CODE REVIEW

**Comment by tarasglek** [comment]
Here is me loading an empty chatcraft chat 
image

**Comment by tarasglek** [comment]
Eg we shouldn't be loading stuff from db that's not visible

**Review by humphd — APPROVED** [review]

**Comment by tarasglek** [comment]
Added a stats command so it can be used on mobile 
image

**Comment by tarasglek** [comment]
> Love how you did it as a slash command

only sane way to get this on mobile

**Pull request merged**
