### PR TITLE
replit support

### PR DESCRIPTION
**Pull request by tarasglek**
Experimenting with bounties there

https://replit.com/@tarasglek1/chatcraftorg

### CODE REVIEW

**Comment by humphd** [comment]
What is this one about, being able to open it on Repl.it?

**Comment by tarasglek** [comment]
yes, just lets one edit on https://replit.com/. However their 500mb RAM is insufficient to bundle react with vite 🤷

**Comment by humphd** [comment]
We could add GitPod / Code Spaces too if you want that style of dev env.

**Comment by tarasglek** [comment]
I'm just experimenting, replit does a lot of PR, but I'm not impressed so far

**Pull request merged**
