### PR TITLE
Fixed icons in the Menu

### LINKED ISSUE #443: Fix icons in new Menu
The way the icons are being done in the new Menu component isn't right.  Here's how it looks in ChakraUI:

Screenshot 2024-02-12 at 9 00 52 PM

And in the new Menu:

Screenshot 2024-02-12 at 9 01 04 PM

Icons should be:

- On the left
- Same colour as the font for the menu item
- Smaller
- Not a button you click (the whole menu item should be clickable)

### PR DESCRIPTION
**Pull request by Rachit1313**
Closes #443 

Based on the issue, Icons should be:
- [x] On the left
- [x] Same colour as the font for the menu item
- [x] Smaller/ same size as the text
- [x] Not a button you click (the whole menu item should be clickable)

Steps Taken to resolve:
- Updated MessageBase component with icon prop to have icons and not IconButtons
- Updated MenuItem component to be in a div aligned to centre and flex for proper alignment and sizing
- Updated color of delete button icon to be similar to the ChakraUI red.400 text

Screenshots:
image

### CODE REVIEW

**Comment by humphd** [comment]
@Rachit1313 please add proper details about this PR, screenshots, how to review it, etc.

**Comment by Rachit1313** [comment]
> @Rachit1313 please add proper details about this PR, screenshots, how to review it, etc.

sure

**Comment by WangGithub0** [comment]
I met this on this branch:
image

but normal on product:
image

**Comment by humphd** [comment]
@Amnish04 can you review this?

**Comment by Rachit1313** [comment]
> I met this on this branch: image
> 
> but normal on product: image

Could you please confirm because I see the same in empty box in both my branch and in production:
branch:
image

production:
image

**Comment by Rachit1313** [comment]
> still have the same issue: image

Not sure as I am still not able to reproduce this, @Amnish04 can you verify this on your side?

**Comment by Amnish04** [comment]
@WangGithub0 I see the same issue in production
image

cc @Rachit1313

**Review by Amnish04 — CHANGES_REQUESTED** [review]
@Rachit1313 The placement and styling looks as expected to me.

But I have some suggestions for how `MenuItem` wrapper is done.

1. Instead of using `style` attribute with divs and spans, I think its better to use the `Box` component from Chakra.
2. Instead of passing `label` as a prop we should probably pass the children to the original component and let it handle as it is configured to.
3. Having an `icon` prop is a good to encapsulate icon positioning since the original component does not support that. But instead of hard coding `margin-right`, we can rather allow users to pass [iconSpacing](https://chakra-ui.com/docs/components/menu/props#menuitem-props) like Chakra MenuItem does.

```tsx
import React, { ReactNode } from "react";
import {
  MenuItem as ReactMenuItem,
  type MenuItemProps as ReactMenuItemProps,
} from "@szhsin/react-menu";
import { Box } from "@chakra-ui/react";

export type MenuItemProps = ReactMenuItemProps & { icon?: ReactNode; iconSpacing?: number };

const MenuItem: React.FC<MenuItemProps> = ({ icon, iconSpacing = 2, children, ...props }) => {
  return (
    <ReactMenuItem {...props}>
      <>
        {icon && (
          <Box marginRight={iconSpacing} as={"span"}>
            {icon}
          </Box>
        )}
        {children}
      </>
    </ReactMenuItem>
  );
};

export default MenuItem;
```

However, these changes would require us to pass labels as `children` as opposed to `props` at existing places, which I believe are mostly in `MessageBase`.
**Example:**
```tsx
<MenuItem onClick={handleCopy} icon={<MdContentCopy />}>
  Copy
</MenuItem>
```

@humphd What do you think about this?

**Comment by humphd** [comment]
@Amnish04 as long as we fix all the call sites to use the right syntax, I think this is fine.

**Comment by Rachit1313** [comment]
@Amnish04 , made the changes based on your suggestion and david's confirmation. Could you please review it.

**Review by Amnish04 — APPROVED** [review]
@Rachit1313 Looks good to me!

**Comment by Rachit1313** [comment]
> @Rachit1313 Looks good to me!

Should I merge it?

**Comment by Amnish04** [comment]
> > @Rachit1313 Looks good to me!
> 
> Should I merge it?

@humphd Are you also okay with this?

**Comment by humphd** [comment]
> > > @Rachit1313 Looks good to me!
> > 
> > 
> > Should I merge it?
> 
> @humphd Are you also okay with this?

You can make a call on stuff like this.

**Review by humphd — APPROVED** [review]

**Comment by Amnish04** [comment]
> You can make a call on stuff like this.

Sure, sorry I didn't know

**Pull request merged**
