### PR TITLE
Sharing UI and Functions

### PR DESCRIPTION
**Pull request by humphd**
This is an initial prototype of "sharing."  Based on discussions in other issues, I'm sure the UI isn't final.  But I need something I can use to iterate on the back-end functions and UX.

I've moved the **Expand** button to the left of the prompt form, and put a **Share** button on the right.  Clicking it opens a menu:

Screenshot 2023-05-21 at 6 53 02 PM

I've moved @steven4354's copy feature from the header to this menu, and also added a way to download the chat as a Markdown file.

If you click **Create Public URL...** it opens a dialog:

Screenshot 2023-05-21 at 6 54 28 PM

When a user hasn't authenticated yet, they will get this initial version of the dialog, showing a button to allow them to sign in with GitHub.  Clicking that will redirect the user to an OAuth page on GitHub, where they can authorize the app.

When they come back, they will be authenticated, and the Share dialog will allow them to click a button to create/get the URL.

I have not tested any of this, esp. the backend functions.  I should write tests for them, but I'm not 100% sure what I want the API to look like yet, so don't want to waste time.  I'm planning to land this on `main` in the coming week when I have some time to hack on it and fix bugs.

In the mean time, please let me know if you see obvious problems you want fixed.

### CODE REVIEW

**Comment by tarasglek** [comment]
I like it.

**Comment by humphd** [comment]
OK, here we go!

**Comment by humphd** [comment]
Screenshot 2023-05-24 at 1 48 21 PM

After fixing two small things, this is working!  NOTE: there is no UI to get the shared chat yet.  I'll do that in a new PR.  I also need to flesh out the UI for sharing more.

**Comment by humphd** [comment]
Improve the sharing UI, added automatic title and summary generation using OpenAI:

Screenshot 2023-05-24 at 3 08 28 PM

This is live on chatcraft.org.  The "load a chat" UI is still TODO.

**Pull request merged**
