### PR TITLE
Data Control setting is seperated from Model Setting

### PR DESCRIPTION
**Pull request by humphd**
Follow-up work to #759 by @gitdevjin.

I've rebased and done my review as a PR instead, making some adjustments to naming.

@gitdevjin, can you take a look and let me know if this is OK to merge?

Screenshot 2024-12-12 at 3 57 58 PM

### CODE REVIEW

**Comment by gitdevjin** [comment]
@humphd This looks much better, and the naming is much clearer now!

**Comment by humphd** [comment]
Thanks @gitdevjin, and thanks for fixing.

**Comment by gitdevjin** [comment]
@humphd It's my honor. I always love contributing to this project. Have a great weekend ^_^

**Comment by gitdevjin** [comment]
@humphd Oh, I am sorry. I just found that there is an typo "Export database to to JSON file" there is two `to`

**Comment by humphd** [comment]
Send a PR

**Pull request merged**
