### PR TITLE
alternative requestAnimationFrame fix

### PR DESCRIPTION
**Pull request by tarasglek**
Fixes https://github.com/tarasglek/chatcraft.org/issues/629
Fixes https://github.com/tarasglek/chatcraft.org/issues/630

Implementing it cos https://github.com/tarasglek/chatcraft.org/pull/638 didnt work for me

### CODE REVIEW

**Comment by tarasglek** [comment]
This currently throttles llm responses to as fast as we can draw..need to make that promise into a member variable so it can buffer multiple tokens while waiting, but dont understand what the token: thing is for

**Comment by humphd** [comment]
Here's a concept for tidying up the code a bit:

```ts
const createStreamOpenAIResponseHandler = () => {
  const buffer: string[] = [];
  let functionName: string = "";
  let functionArgs: string = "";
  let maxWaitTimeMS = 0;
  let waitingTokens: string[] = [];
  let streamOpenAIResponsePromise: Promise<void> | null = null;

  const handleTokenRendering = (): Promise<void> => {
    const startTime = performance.now();
    return new Promise((resolve) => {
      requestAnimationFrame(() => {
        onData({
          token: waitingTokens.join(""),
          currentText: buffer.join(""),
        });
        if (waitingTokens.length > 1) {
          console.log("waitingTokens", waitingTokens.length);
        }
        waitingTokens = [];
        const endTime = performance.now();
        const waitTime = endTime - startTime;
        if (waitTime > maxWaitTimeMS && waitTime > 16) {
          maxWaitTimeMS = waitTime;
          console.log("streamOpenAIResponse maxWaitTimeMS", maxWaitTimeMS);
        }
        streamOpenAIResponsePromise = null;
        resolve();
      });
    });
  };

  const streamOpenAIResponse = async (
    token: string,
    func: string,
    args: string
  ): Promise<void> => {
    if (func || args) {
      functionName += func;
      functionArgs += args;
      if (onData && !isPaused) {
        onData({ token: func, currentText: functionArgs });
      }
    } else if (token) {
      buffer.push(token);
      if (onData && !isPaused) {
        waitingTokens.push(token);
        if (!streamOpenAIResponsePromise) {
          streamOpenAIResponsePromise = handleTokenRendering();
        }
      }
    }
  };

  const chunkStream = async (
    streamResponse: Stream<ChatCompletionChunk>
  ): Promise<void> => {
    for await (const streamChunk of streamResponse) {
      const parsedData = parseOpenAIChunkResponse(streamChunk);
      await streamOpenAIResponse(
        parsedData.token,
        parsedData.functionName,
        parsedData.functionArgs
      );
    }
  };

  const renderResponse = async (): Promise<void> => {
    if (streamOpenAIResponsePromise) {
      await streamOpenAIResponsePromise;
    }
    const content = buffer.join("");
    return handleOpenAIResponse(content, functionName, functionArgs);
  };

  return { chunkStream, renderResponse };
};

const { chunkStream, renderResponse } = createStreamOpenAIResponseHandler();

const handleStreamingResponse = async (
  streamResponse: Stream<ChatCompletionChunk>
): Promise<void> => {
  await chunkStream(streamResponse);
  await renderResponse();
};
```

**Comment by tarasglek** [comment]
I'm ok with however you want to structure this code. Please change to your liking and land?

**Comment by humphd** [comment]
I think this is great.  Thanks for your help iterating on the idea.  I couldn't get an rAF-based version to work this well.

**Pull request merged**
